### ISSUE TITLE
Will the armv7 builds be back?

### ISSUE THREAD

**Issue by jjvdgeer** [flosoft/docker-joplin-server#10]
I tried updating my joplin docker image today but found out there was no armv7 build anymore. This is confirmed by the last checkin that removes the armv7 build. Will they be back? Hope so...

**Comment by flosoft** [comment]
Sadly one of the dependencies (cmake) is not available, so the build fails. I'll be trying to fix this, but haven't found a workaround just yet.

**Comment by jjvdgeer** [comment]
OK, thanks. Good luck! :)

**Comment by rogatty** [comment]
@flosoft I've added `cmake` to:
https://github.com/flosoft/docker-joplin-server/blob/a9e6718da7c91da9057477aaa50b4fb0e87a6856/Dockerfile#L13
and it built the `linux/arm/v7` image just fine.

**Comment by flosoft** [comment]
The image is now available. In the future, I should limit adding cmake to the armv7 build only.

https://github.com/flosoft/docker-joplin-server/actions/runs/1512754211

**Comment by rogatty** [comment]
Thanks!

**Comment by jjvdgeer** [comment]
Thanks! :)
