### ISSUE TITLE
Miss-spelling of BUILD_SEQUENTIAL instruction on line 45 of Dockerfile

### ISSUE THREAD

**Issue by davemguru** [flosoft/docker-joplin-server#12]
I am very new to this. I was just reading your dockerfile and at line 45 it says "run BUILD_SEQUENCIAL=1 ....."
I believe that the instruction is spelt BUILD_SEQUENTIAL. But, I may be wrong. It could be that this spelling is either a different instruction to some other process I am unaware of. Or it could be that this spelling is accepted by the current version of Docker.
I am using your Docker compose for arm7 (Odroid XU4) that I am attempting to setup Joplin server on.
Apologies if I have raised an error that is incorrect.
David

**Comment by flosoft** [comment]
Looking at the code, it's correct the way it is mis-spelled.

https://github.com/laurent22/joplin/search?q=BUILD_SEQUENCIAL
