### ISSUE TITLE
Node 18 not used for final stage

### ISSUE THREAD

**Issue by maresmar** [flosoft/docker-joplin-server#24]
Hi,

I noticed you are using node-18 only for build stage, but the final stage is still node-16. Is there a reason for that? I am unable to setup ARM building on my machine, so I cannot test it to create a PR.

https://github.com/flosoft/docker-joplin-server/blob/df30d6a168c66ca992d8cac96b732e53d0afda5d/Dockerfile#L55

Thank you for the image for ARM!
Martin

**Comment by flosoft** [comment]
great point. Fixed it.
https://github.com/flosoft/docker-joplin-server/pull/25
