### ISSUE TITLE
Help needed to get this running

### ISSUE THREAD

**Issue by seatrout** [flosoft/docker-joplin-server#3]
This is a really simple and ignorant question. Bear with me, please. 

I know how to clone this code or download it, but what must I do to get the server actually up and running? What files go where, and what commands actuate them?

(I'm running 64bit ubuntu server on a Pi 4 if that makes any difference)

**Comment by flosoft** [comment]
The easiest would be to go simply use the docker-compose exampe listed in the README - https://github.com/flosoft/docker-joplin-server#generic-docker-composeyml

This will download the pre-built image for you.

Basically, put the example above in a folder as `docker-compose.yml` and then run `docker-compose up -d`

**Comment by seatrout** [comment]
thank you!

**Comment by seatrout** [comment]
And if I wanted the one with traefik, would I have to get a traefik instance running first in another docker container?

**Comment by flosoft** [comment]
Indeed - you would need to set up traefik yourself.
