### ISSUE TITLE
Build of 3.14.1 failed

### ISSUE THREAD

**Issue by maresmar** [flosoft/docker-joplin-server#38]
Hi,

it looks like the build for [3.14.1](https://joplinapp.org/help/about/changelog/server#server-v2141---2023-12-17t150752z) wasn't successful with:

```
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c BUILD_SEQUENCIAL=1 yarn install --inline-builds     && yarn cache clean     && rm -rf .yarn/berry" did not complete successfully: exit code: 1
```

see https://github.com/flosoft/docker-joplin-server/actions/runs/7239381985

**Comment by flosoft** [comment]
This has been resolved.
