### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cybrpimp** [flosoft/docker-joplin-server#6]
I used the default example docker-compose.yml on the main page and got this error;

Any suggestions?

![image](https://user-images.githubusercontent.com/61793417/124440913-0101dc80-dd30-11eb-9403-6b43be47bd86.png)

**Comment by flosoft** [comment]
you will need to have a network called `traefik_default` on your docker instance already.
If you're not using traefik, you'll need to connect it to the network of your web frontend.

**Comment by cybrpimp** [comment]
@flosoft Thanks Forian for the response.

My plan is to add a load balancer in front of our server that has SSL cert for everything on our server so I'm thinking the traefik would not be needed, but I'm not that good with Docker.

Is there another Docker Compose file that would be better to start with?
